version: "3"
services:
  php:
    tty: true # to keep container started
    build: .
    volumes:
      - ${MOUNT_PATH}:/project
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      PHP_IDE_CONFIG: serverName=localhost